name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  harden_security:
    name: Check used GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Ensure all Actions are pinned to a Commit SHA
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@ed00f72a3ca5b6eff8ad4d3ffdcacedb67a21db1

  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Build
        uses: ./.github/actions/build
        with:
          node-version: ${{ matrix.node-version }}
      - name: Save Turborepo cache
        uses: actions/cache/save@6849a6489940f00c2f30c0fb92c6274307ccb58a
        with:
          path: .turbo
          key: turbo-${{ runner.os }}-node-${{ matrix.node-version }}-${{ github.sha }}

  format:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dev dependencies
        run: pnpm install --dev
      - name: Check code style
        run: pnpm format:check
